// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-axios'
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query'
import type {
  GetMyselfApiCustomerMyselfGetData,
  UpdateCustomerApiCustomerCustomerIdPutData,
  UpdateCustomerApiCustomerCustomerIdPutError,
  UpdateCustomerApiCustomerCustomerIdPutResponse,
  ListCustomersApiCustomerGetData,
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData,
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostError,
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponse,
  IntakeStreamRouteApiIntakeStreamPostData,
  IntakeStreamRouteApiIntakeStreamPostError,
  PingRunRouteApiPingRunPostData,
  PingRunRouteApiPingRunPostError,
  PingRunRouteApiPingRunPostResponse,
  UpkeepStreamRouteApiUpkeepStreamPostData,
  UpkeepStreamRouteApiUpkeepStreamPostError
} from '../types.gen'
import {
  client,
  getMyselfApiCustomerMyselfGet,
  updateCustomerApiCustomerCustomerIdPut,
  listCustomersApiCustomerGet,
  resetCustomerHistoryApiCustomerCustomerIdResetHistoryPost,
  intakeStreamRouteApiIntakeStreamPost,
  pingRunRouteApiPingRunPost,
  upkeepStreamRouteApiUpkeepStreamPost
} from '../sdk.gen'
import type { AxiosError } from 'axios'

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return params
}

export const getMyselfApiCustomerMyselfGetQueryKey = (
  options?: Options<GetMyselfApiCustomerMyselfGetData>
) => [createQueryKey('getMyselfApiCustomerMyselfGet', options)]

export const getMyselfApiCustomerMyselfGetOptions = (
  options?: Options<GetMyselfApiCustomerMyselfGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyselfApiCustomerMyselfGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: getMyselfApiCustomerMyselfGetQueryKey(options)
  })
}

export const updateCustomerApiCustomerCustomerIdPutMutation = (
  options?: Partial<Options<UpdateCustomerApiCustomerCustomerIdPutData>>
) => {
  const mutationOptions: UseMutationOptions<
    UpdateCustomerApiCustomerCustomerIdPutResponse,
    AxiosError<UpdateCustomerApiCustomerCustomerIdPutError>,
    Options<UpdateCustomerApiCustomerCustomerIdPutData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await updateCustomerApiCustomerCustomerIdPut({
        ...options,
        ...localOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const listCustomersApiCustomerGetQueryKey = (
  options?: Options<ListCustomersApiCustomerGetData>
) => [createQueryKey('listCustomersApiCustomerGet', options)]

export const listCustomersApiCustomerGetOptions = (
  options?: Options<ListCustomersApiCustomerGetData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCustomersApiCustomerGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: listCustomersApiCustomerGetQueryKey(options)
  })
}

export const resetCustomerHistoryApiCustomerCustomerIdResetHistoryPostQueryKey =
  (
    options: Options<ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData>
  ) => [
    createQueryKey(
      'resetCustomerHistoryApiCustomerCustomerIdResetHistoryPost',
      options
    )
  ]

export const resetCustomerHistoryApiCustomerCustomerIdResetHistoryPostOptions =
  (
    options: Options<ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData>
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await resetCustomerHistoryApiCustomerCustomerIdResetHistoryPost({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
          })
        return data
      },
      queryKey:
        resetCustomerHistoryApiCustomerCustomerIdResetHistoryPostQueryKey(
          options
        )
    })
  }

export const resetCustomerHistoryApiCustomerCustomerIdResetHistoryPostMutation =
  (
    options?: Partial<
      Options<ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData>
    >
  ) => {
    const mutationOptions: UseMutationOptions<
      ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponse,
      AxiosError<ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostError>,
      Options<ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData>
    > = {
      mutationFn: async localOptions => {
        const { data } =
          await resetCustomerHistoryApiCustomerCustomerIdResetHistoryPost({
            ...options,
            ...localOptions,
            throwOnError: true
          })
        return data
      }
    }
    return mutationOptions
  }

export const intakeStreamRouteApiIntakeStreamPostQueryKey = (
  options: Options<IntakeStreamRouteApiIntakeStreamPostData>
) => [createQueryKey('intakeStreamRouteApiIntakeStreamPost', options)]

export const intakeStreamRouteApiIntakeStreamPostOptions = (
  options: Options<IntakeStreamRouteApiIntakeStreamPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await intakeStreamRouteApiIntakeStreamPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: intakeStreamRouteApiIntakeStreamPostQueryKey(options)
  })
}

export const intakeStreamRouteApiIntakeStreamPostMutation = (
  options?: Partial<Options<IntakeStreamRouteApiIntakeStreamPostData>>
) => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<IntakeStreamRouteApiIntakeStreamPostError>,
    Options<IntakeStreamRouteApiIntakeStreamPostData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await intakeStreamRouteApiIntakeStreamPost({
        ...options,
        ...localOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const pingRunRouteApiPingRunPostQueryKey = (
  options?: Options<PingRunRouteApiPingRunPostData>
) => [createQueryKey('pingRunRouteApiPingRunPost', options)]

export const pingRunRouteApiPingRunPostOptions = (
  options?: Options<PingRunRouteApiPingRunPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await pingRunRouteApiPingRunPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: pingRunRouteApiPingRunPostQueryKey(options)
  })
}

export const pingRunRouteApiPingRunPostMutation = (
  options?: Partial<Options<PingRunRouteApiPingRunPostData>>
) => {
  const mutationOptions: UseMutationOptions<
    PingRunRouteApiPingRunPostResponse,
    AxiosError<PingRunRouteApiPingRunPostError>,
    Options<PingRunRouteApiPingRunPostData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await pingRunRouteApiPingRunPost({
        ...options,
        ...localOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}

export const upkeepStreamRouteApiUpkeepStreamPostQueryKey = (
  options: Options<UpkeepStreamRouteApiUpkeepStreamPostData>
) => [createQueryKey('upkeepStreamRouteApiUpkeepStreamPost', options)]

export const upkeepStreamRouteApiUpkeepStreamPostOptions = (
  options: Options<UpkeepStreamRouteApiUpkeepStreamPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await upkeepStreamRouteApiUpkeepStreamPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: upkeepStreamRouteApiUpkeepStreamPostQueryKey(options)
  })
}

export const upkeepStreamRouteApiUpkeepStreamPostMutation = (
  options?: Partial<Options<UpkeepStreamRouteApiUpkeepStreamPostData>>
) => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<UpkeepStreamRouteApiUpkeepStreamPostError>,
    Options<UpkeepStreamRouteApiUpkeepStreamPostData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await upkeepStreamRouteApiUpkeepStreamPost({
        ...options,
        ...localOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}
