"""add is_activated to users

Revision ID: 2b387e107ed3
Revises: 2e31d71c7a02
Create Date: 2026-03-17 18:41:47.351663

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2b387e107ed3"
down_revision = "2e31d71c7a02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_activated", sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_activated")
    # ### end Alembic commands ###
