"""add_content_type_to_documents

Revision ID: 2e31d71c7a02
Revises: 22a499764c49
Create Date: 2026-01-30 15:22:03.327914

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e31d71c7a02"
down_revision = "22a499764c49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value for existing rows
    op.add_column("documents", sa.Column("content_type", sa.String(), nullable=False, server_default="personal_note"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "content_type")
    # ### end Alembic commands ###
