"""add_user_personalization_fields

Revision ID: a76a94f86085
Revises: ea0e68d7a2fe
Create Date: 2026-01-21 19:43:14.189321

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a76a94f86085"
down_revision = "ea0e68d7a2fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("custom_instructions", sa.String(), nullable=True))
    op.add_column("users", sa.Column("nickname", sa.String(), nullable=True))
    op.add_column("users", sa.Column("occupation", sa.String(), nullable=True))
    op.add_column("users", sa.Column("about_you", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "about_you")
    op.drop_column("users", "occupation")
    op.drop_column("users", "nickname")
    op.drop_column("users", "custom_instructions")
    # ### end Alembic commands ###
