"""add age_of_first_reuben field

Revision ID: b334686433df
Revises: f99f8b81c0bc
Create Date: 2026-01-23 01:52:59.482821

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b334686433df"
down_revision = "f99f8b81c0bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age_of_first_reuben", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "age_of_first_reuben")
    # ### end Alembic commands ###
