"""add_title_to_threads

Revision ID: ea0e68d7a2fe
Revises: a1910db1ca87
Create Date: 2026-01-13 17:45:50.204546

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea0e68d7a2fe"
down_revision = "a1910db1ca87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("threads", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threads", "title")
    # ### end Alembic commands ###
