"""add search_vector for hybrid full-text search

Revision ID: f998338707ad
Revises: 2b387e107ed3
Create Date: 2026-03-30 20:35:36.699142

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f998338707ad"
down_revision = "2b387e107ed3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_chunks", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True))
    op.create_index(
        "ix_document_chunks_search_vector", "document_chunks", ["search_vector"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_chunks_search_vector", table_name="document_chunks", postgresql_using="gin")
    op.drop_column("document_chunks", "search_vector")
    # ### end Alembic commands ###
