// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios'
import type {
  GetMyselfApiCustomerMyselfGetData,
  GetMyselfApiCustomerMyselfGetResponse,
  UpdateCustomerApiCustomerCustomerIdPutData,
  UpdateCustomerApiCustomerCustomerIdPutError,
  UpdateCustomerApiCustomerCustomerIdPutResponse,
  ListCustomersApiCustomerGetData,
  ListCustomersApiCustomerGetResponse,
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData,
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostError,
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponse,
  IntakeStreamRouteApiIntakeStreamPostData,
  IntakeStreamRouteApiIntakeStreamPostError,
  PingRunRouteApiPingRunPostData,
  PingRunRouteApiPingRunPostError,
  PingRunRouteApiPingRunPostResponse,
  UpkeepStreamRouteApiUpkeepStreamPostData,
  UpkeepStreamRouteApiUpkeepStreamPostError
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Get Myself
 * Get a customer by ID.
 */
export const getMyselfApiCustomerMyselfGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetMyselfApiCustomerMyselfGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetMyselfApiCustomerMyselfGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    url: '/api/customer/myself'
  })
}

/**
 * Update Customer
 * Update an existing customer.
 */
export const updateCustomerApiCustomerCustomerIdPut = <
  ThrowOnError extends boolean = false
>(
  options: Options<UpdateCustomerApiCustomerCustomerIdPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    UpdateCustomerApiCustomerCustomerIdPutResponse,
    UpdateCustomerApiCustomerCustomerIdPutError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers
    },
    url: '/api/customer/{user_id}'
  })
}

/**
 * List Customers
 * List all customers.
 */
export const listCustomersApiCustomerGet = <
  ThrowOnError extends boolean = false
>(
  options?: Options<ListCustomersApiCustomerGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListCustomersApiCustomerGetResponse,
    unknown,
    ThrowOnError
  >({
    ...options,
    url: '/api/customer'
  })
}

/**
 * Reset Customer History
 * Reset customer history to default values.
 *
 * Resets:
 * - intake_survey to initial state (started=False, all fields cleared)
 * - plaid_data to default seed data
 */
export const resetCustomerHistoryApiCustomerCustomerIdResetHistoryPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponse,
    ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostError,
    ThrowOnError
  >({
    ...options,
    url: '/api/customer/{user_id}/reset-history'
  })
}

/**
 * Intake Stream
 * Intake agent streaming endpoint.
 *
 * Handles intake survey questions and generates initial financial plan.
 * Use this endpoint when customer has not completed intake survey yet.
 *
 * Args:
 * message: User message containing query and thread_id
 *
 * Returns:
 * Server-Sent Events stream of agent responses
 */
export const intakeStreamRouteApiIntakeStreamPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<IntakeStreamRouteApiIntakeStreamPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    IntakeStreamRouteApiIntakeStreamPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers
    },
    url: '/api/intake/stream'
  })
}

/**
 * Ping Run
 * Non-streaming ping agent endpoint for testing.
 *
 * Provides proactive financial notification response based on customer data.
 * Creates a new thread for this proactive notification.
 *
 * Args:
 * user_id: Customer ID
 * evaluate: If True, evaluates notification and includes should_send in metadata
 *
 * Returns:
 * AssistantMessage with agent response and metadata (includes generated thread_id)
 *
 * Raises:
 * HTTPException: If no response is generated from the agent
 */
export const pingRunRouteApiPingRunPost = <
  ThrowOnError extends boolean = false
>(
  options?: Options<PingRunRouteApiPingRunPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PingRunRouteApiPingRunPostResponse,
    PingRunRouteApiPingRunPostError,
    ThrowOnError
  >({
    ...options,
    url: '/api/ping/run'
  })
}

/**
 * Upkeep Stream
 * Upkeep agent streaming endpoint.
 *
 * Provides ongoing financial maintenance and advice.
 * Use this endpoint after customer has completed intake survey.
 *
 * Args:
 * message: User message containing query and thread_id
 *
 * Returns:
 * Server-Sent Events stream of agent responses
 */
export const upkeepStreamRouteApiUpkeepStreamPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<UpkeepStreamRouteApiUpkeepStreamPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    unknown,
    UpkeepStreamRouteApiUpkeepStreamPostError,
    ThrowOnError
  >({
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers
    },
    url: '/api/upkeep/stream'
  })
}
