// This file is auto-generated by @hey-api/openapi-ts

export type AssistantMessage = {
  thread_id: string
  metadata?: MessageMetadata
  role?: 'assistant'
  content: string
}

/**
 * Complete customer profile with all financial and survey data.
 *
 * This is the top-level model that aggregates all customer information
 * and will be passed to the agent via RunContext[Customer].
 */
export type UserSchemaInput = {
  /**
   * Unique customer identifier
   */
  user_id: string
  /**
   * Customer's email
   */
  email: string
  /**
   * Customer's name
   */
  name: string
  /**
   * When this customer profile was created
   */
  created_at: string
  /**
   * When this customer profile was last updated
   */
  updated_at: string
  /**
   * Customer's credit report data as formatted text
   */
  credit_report?: string | null
  /**
   * Customer's banking and spending data as formatted text
   */
  plaid_data?: string | null
  /**
   * Additional feature metadata as formatted text
   */
  feature_metadata?: string | null
  /**
   * Intake survey where agent manages flow to populate responses and generate a financial plan
   */
  intake_survey?: IntakeSurvey | null
}

/**
 * Complete customer profile with all financial and survey data.
 *
 * This is the top-level model that aggregates all customer information
 * and will be passed to the agent via RunContext[Customer].
 */
export type UserSchemaOutput = {
  /**
   * Unique customer identifier
   */
  user_id: string
  /**
   * Customer's email
   */
  email: string
  /**
   * Customer's name
   */
  name: string
  /**
   * When this customer profile was created
   */
  created_at: string
  /**
   * When this customer profile was last updated
   */
  updated_at: string
  /**
   * Customer's credit report data as formatted text
   */
  credit_report?: string | null
  /**
   * Customer's banking and spending data as formatted text
   */
  plaid_data?: string | null
  /**
   * Additional feature metadata as formatted text
   */
  feature_metadata?: string | null
  /**
   * Intake survey where agent manages flow to populate responses and generate a financial plan
   */
  intake_survey?: {
    [key: string]: unknown
  } | null
}

export type HttpValidationError = {
  detail?: Array<ValidationError>
}

export type HealthCheckResponse = {
  status: string
}

/**
 * Intake survey where agent manages full conversation flow.
 *
 * The frontend displays an opening question, then the agent asks 3 core questions
 * and generates a plan in one conversation, without structured Q&A tracking.
 */
export type IntakeSurvey = {
  /**
   * Whether the user has started the intake survey
   */
  started?: boolean
  /**
   * Timestamp when survey conversation started
   */
  started_at?: string | null
  /**
   * Whether the agent has generated the initial financial plan
   */
  plan_generated?: boolean
  /**
   * Timestamp when plan was generated
   */
  plan_generated_at?: string | null
  /**
   * Whether the user has confirmed the generated financial plan
   */
  plan_confirmed?: boolean
  /**
   * User's response to the opening question about their 3-month financial vision
   */
  opening_question_response?: string | null
  /**
   * User's response about why they want to make a change now
   */
  question_1_response?: string | null
  /**
   * User's response about where their money goes each month
   */
  question_2_response?: string | null
  /**
   * User's response about what obstacles prevent them from sticking to money goals
   */
  question_3_response?: string | null
  /**
   * The initial financial plan generated by the agent after completing the intake survey
   */
  generated_plan?: string | null
}

export type MessageMetadata = {
  original_llm_response?: string | null
  should_send?: boolean | null
}

export type UserMessage = {
  thread_id: string
  metadata?: MessageMetadata
  role?: 'user'
  content: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type GetMyselfApiCustomerMyselfGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/customer/myself'
}

export type GetMyselfApiCustomerMyselfGetResponses = {
  /**
   * Successful Response
   */
  200: UserSchemaOutput
}

export type GetMyselfApiCustomerMyselfGetResponse =
  GetMyselfApiCustomerMyselfGetResponses[keyof GetMyselfApiCustomerMyselfGetResponses]

export type UpdateCustomerApiCustomerCustomerIdPutData = {
  body: UserSchemaInput
  path: {
    user_id: string
  }
  query?: never
  url: '/api/customer/{user_id}'
}

export type UpdateCustomerApiCustomerCustomerIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateCustomerApiCustomerCustomerIdPutError =
  UpdateCustomerApiCustomerCustomerIdPutErrors[keyof UpdateCustomerApiCustomerCustomerIdPutErrors]

export type UpdateCustomerApiCustomerCustomerIdPutResponses = {
  /**
   * Successful Response
   */
  200: UserSchemaOutput
}

export type UpdateCustomerApiCustomerCustomerIdPutResponse =
  UpdateCustomerApiCustomerCustomerIdPutResponses[keyof UpdateCustomerApiCustomerCustomerIdPutResponses]

export type ListCustomersApiCustomerGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/customer'
}

export type ListCustomersApiCustomerGetResponses = {
  /**
   * Successful Response
   */
  200: Array<UserSchemaOutput>
}

export type ListCustomersApiCustomerGetResponse =
  ListCustomersApiCustomerGetResponses[keyof ListCustomersApiCustomerGetResponses]

export type ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostData = {
  body?: never
  path: {
    user_id: string
  }
  query?: never
  url: '/api/customer/{user_id}/reset-history'
}

export type ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostError =
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostErrors[keyof ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostErrors]

export type ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponses =
  {
    /**
     * Successful Response
     */
    200: UserSchemaOutput
  }

export type ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponse =
  ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponses[keyof ResetCustomerHistoryApiCustomerCustomerIdResetHistoryPostResponses]

export type IntakeStreamRouteApiIntakeStreamPostData = {
  body: UserMessage
  path?: never
  query?: never
  url: '/api/intake/stream'
}

export type IntakeStreamRouteApiIntakeStreamPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type IntakeStreamRouteApiIntakeStreamPostError =
  IntakeStreamRouteApiIntakeStreamPostErrors[keyof IntakeStreamRouteApiIntakeStreamPostErrors]

export type IntakeStreamRouteApiIntakeStreamPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type PingRunRouteApiPingRunPostData = {
  body?: never
  path?: never
  query?: {
    evaluate?: boolean
  }
  url: '/api/ping/run'
}

export type PingRunRouteApiPingRunPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PingRunRouteApiPingRunPostError =
  PingRunRouteApiPingRunPostErrors[keyof PingRunRouteApiPingRunPostErrors]

export type PingRunRouteApiPingRunPostResponses = {
  /**
   * Successful Response
   */
  200: AssistantMessage
}

export type PingRunRouteApiPingRunPostResponse =
  PingRunRouteApiPingRunPostResponses[keyof PingRunRouteApiPingRunPostResponses]

export type UpkeepStreamRouteApiUpkeepStreamPostData = {
  body: UserMessage
  path?: never
  query?: never
  url: '/api/upkeep/stream'
}

export type UpkeepStreamRouteApiUpkeepStreamPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpkeepStreamRouteApiUpkeepStreamPostError =
  UpkeepStreamRouteApiUpkeepStreamPostErrors[keyof UpkeepStreamRouteApiUpkeepStreamPostErrors]

export type UpkeepStreamRouteApiUpkeepStreamPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
